### ISSUE TITLE
Evaluate keywords/identifiers 'true' and 'false' to expressions

### ISSUE THREAD

**Issue by density215** [NLnetLabs/roto#29]
Right now you in roto you cannot create a sub-term expression that always returns the value true, or false, by just stating 'true;' or 'false;'. You are forced to create a compare expression, e.g. '1 == 1;', which is kinda' sutpid and a waste of VM cycles.

**Comment by tertsdiepraam** [comment]
This has been fixed as part of https://github.com/NLnetLabs/roto/pull/48
