### ISSUE TITLE
None of the builtin primitives is marked to be 'copy' 

### ISSUE THREAD

**Issue by DRiKE** [NLnetLabs/roto#53]
Based on the big-overhaul branch, a4002c5

This is not breaking anything for me, but simply caught my eye. It seems that none of the primitives has `.is_copy_type` set to `true`.
Registering our own type as being 'copy' does work however, for what that's worth:

```
#[test]
fn issue_53() {
    let mut rt = Runtime::basic().unwrap();
    // this fails:
    assert!(
        rt.runtime_types.iter().any(|t| t.is_copy_type)
    );


    #[derive(Copy, Clone)]
    struct Foo { _x: u32 }

    rt.register_copy_type::<Foo>().unwrap();
    // but this will pass:
    assert!(
        rt.runtime_types.iter().any(|t| t.is_copy_type)
    );
}
```

**Comment by tertsdiepraam** [comment]
IIRC, the `copy` field is unused at the moment and it might stay that way, because they're kind of tricky. But yeah, they should all be copy :)
